

export const metadata = {
  title: "Velox App",
  description: "Generated by create next app",
};

// app/admin/layout.js
export default function AdminLayout({ children }) {
  console.log("AdminLayout rendering");
  return <div>{children}</div>;
}